import ast
import streamlit as st
import pandas as pd
import plotly.express as px
import requests
from utils import load_students
from database import (
    insert_intervention,
    approve_intervention,
    reject_intervention,
    get_latest_approved,
)

st.title("👤 Student Detail View")
st.caption("Select a student to see their full risk profile")

df = load_students()

# ── Student selector ──────────────────────────────────────────────────────────
selected_id = st.selectbox("Select student", sorted(df["student_id"].tolist()))
student = df[df["student_id"] == selected_id].iloc[0]

# ── Clear session state when student changes ──────────────────────────────────
if st.session_state.get("_active_student") != selected_id:
    st.session_state["_active_student"] = selected_id
    for key in ["intervention_plan", "intervention_id", "approval_status"]:
        st.session_state.pop(key, None)

st.divider()

# ── Key metrics ───────────────────────────────────────────────────────────────
col1, col2, col3 = st.columns(3)
col1.metric("CGPA",                  student["cgpa"])
col2.metric("Attendance",            f"{student['attendance_percentage']}%")
col3.metric("Prediction Confidence", f"{student['prediction_confidence']:.1f}")

col4, col5, col6 = st.columns(3)
col4.metric("Backlogs",       student["backlog_count"])
col5.metric("Fee Delay Days", student["fee_delay_days"])
col6.metric("Risk Band",      student["risk_band"].upper())

st.divider()

# ── Profile info ──────────────────────────────────────────────────────────────
info_col1, info_col2 = st.columns(2)
with info_col1:
    st.write("**Department:**", student["department"])
with info_col2:
    st.write("**Year:**",       student["year_label"])

st.divider()

# ── Top contributing factors (SHAP-based) ─────────────────────────────────────
st.subheader("Top Contributing Factors")
st.caption("Based on the model's SHAP analysis — shows what the model relied on most for this prediction, not a guaranteed cause")

top_factors_raw = student.get("top_factors", "[]")
top_factors = ast.literal_eval(top_factors_raw) if isinstance(top_factors_raw, str) else top_factors_raw

if top_factors:
    factors_df = pd.DataFrame(top_factors)
    fig = px.bar(
        factors_df,
        x="importance",
        y="feature",
        orientation="h",
        title=f"Top factors for {selected_id}",
        text="value"
    )
    fig.update_layout(yaxis={'categoryorder': 'total ascending'})
    st.plotly_chart(fig, use_container_width=True)
else:
    st.write("No factor breakdown available for this student.")

st.divider()

# ── Intervention Plan ─────────────────────────────────────────────────────────
st.subheader("📋 Intervention Plan")
st.caption("Generated by the Mentor Agent — click below to fetch a plan for this student")

MENTOR_AGENT_URL = "https://sar-mentor-agent.onrender.com/generate-intervention"

# ── Fetch button ──────────────────────────────────────────────────────────────
if st.button("Get Intervention Plan", key="get_intervention"):
    with st.spinner("Contacting Mentor Agent..."):
        try:
            resp = requests.post(
                MENTOR_AGENT_URL,
                json={"student_id": selected_id},
                timeout=60,
            )
            resp.raise_for_status()
            plan = resp.json()

            # Step 1 — store in DB as pending_approval, get back the intervention_id
            intervention_id = insert_intervention(selected_id, plan)

            # Step 2 — persist in session state so buttons below can reference them
            st.session_state["intervention_plan"]  = plan
            st.session_state["intervention_id"]    = intervention_id
            st.session_state["approval_status"]    = "pending_approval"

        except requests.exceptions.ConnectionError:
            st.error("Could not reach the Mentor Agent. Make sure Person B's server is running on port 8001.")
        except requests.exceptions.Timeout:
            st.error("Request timed out. The Mentor Agent took too long to respond.")
        except requests.exceptions.HTTPError as e:
            st.error(f"Mentor Agent returned an error: {e}")
        except Exception as e:
            st.error(f"Unexpected error: {e}")

# ── Display plan + Approve / Reject ──────────────────────────────────────────
if "intervention_plan" in st.session_state:
    plan            = st.session_state["intervention_plan"]
    intervention_id = st.session_state["intervention_id"]
    approval_status = st.session_state.get("approval_status", "pending_approval")

    # ── Summary card ──────────────────────────────────────────────────────────
    st.markdown("**Student Summary**")
    st.info(plan.get("student_summary", "—"))

    # ── Risk + priority badges ────────────────────────────────────────────────
    b1, b2 = st.columns(2)
    b1.metric("Risk Band",      plan.get("risk_band",      "—"))
    b2.metric("Priority Level", plan.get("priority_level", "—"))

    st.divider()

    # ── Recommended actions ───────────────────────────────────────────────────
    st.markdown("**Recommended Actions**")
    actions = plan.get("recommended_actions", [])
    if actions:
        for i, action in enumerate(actions, 1):
            st.markdown(f"{i}. {action}")
    else:
        st.write("No actions returned.")

    st.divider()

    # ── Follow-up plan ────────────────────────────────────────────────────────
    st.markdown("**Follow-up Plan**")
    st.warning(plan.get("follow_up_plan", "—"))

    st.divider()

    # ── Approval status + buttons ─────────────────────────────────────────────
    st.markdown("**Approval Status**")

    if approval_status == "pending_approval":
        st.markdown("🟡 **Pending Approval**")

        from utils import MENTOR_LIST

        faculty_name = st.selectbox(
            "Your name (required to approve)",
            options=["-- Select --"] + MENTOR_LIST,
            key="faculty_name_input",
        )

        approve_col, reject_col = st.columns(2)

        with approve_col:
            if st.button("✅ Approve", use_container_width=True, key="approve_btn"):
                if faculty_name == "-- Select --":
                    st.warning("Please enter your name before approving.")
                else:
                    # Step 2a — UPDATE same row: status=approved, approved_by, approved_at
                    approve_intervention(intervention_id, faculty_name.strip())
                    st.session_state["approval_status"] = "approved"
                    st.rerun()

        with reject_col:
            if st.button("❌ Reject", use_container_width=True, key="reject_btn"):
                # Step 2b — UPDATE same row: status=rejected only
                reject_intervention(intervention_id)
                st.session_state["approval_status"] = "rejected"
                st.rerun()

    elif approval_status == "approved":
        st.success("🟢 Approved")

    elif approval_status == "rejected":
        st.error("🔴 Rejected — fetch a new plan if needed.")

st.divider()

# ── Latest approved intervention on record ────────────────────────────────────
# Shows what is currently approved in DB for this student.
# This is what Person D fetches via GET /intervention/{student_id}.
st.subheader("✅ Latest Approved Intervention on Record")

# Column order from DB:
# 0  intervention_id  1  student_id     2  risk_band
# 3  prediction_conf  4  student_summary 5  recommended_actions
# 6  priority_level   7  follow_up_plan  8  status
# 9  approved_by      10 approved_at     11 generated_at

approved = get_latest_approved(selected_id)
if approved:
    st.info(f"**Summary:** {approved[4]}")
    rc1, rc2, rc3 = st.columns(3)
    rc1.metric("Risk Band",   approved[2] or "—")
    rc2.metric("Priority",    approved[6] or "—")
    rc3.metric("Approved By", approved[9] or "—")
    st.caption(f"Approved at: {approved[10]}  |  Generated at: {approved[11]}")
else:
    st.caption("No approved intervention on record for this student yet.")