import streamlit as st
import pandas as pd
import plotly.express as px
from utils import load_students

st.title("👤 Student Detail View")
st.caption("Select a student to see their full risk profile")

df = load_students()

# ── Student selector ──────────────────────────────────────────────────────────
selected_id = st.selectbox("Select student", sorted(df["student_id"].tolist()))
student = df[df["student_id"] == selected_id].iloc[0]

st.divider()

# ── Key metrics ───────────────────────────────────────────────────────────────
col1, col2, col3 = st.columns(3)
col1.metric("CGPA",            student["cgpa"])
col2.metric("Attendance",      f"{student['attendance_percentage']}%")
col3.metric("Risk Score",      student["risk_score"])

col4, col5, col6 = st.columns(3)
col4.metric("Backlogs",        student["backlog_count"])
col5.metric("Fee Delay Days",  student["fee_delay_days"])
col6.metric("Risk Band",       student["risk_band"].upper())

st.divider()

# ── Profile info ──────────────────────────────────────────────────────────────
info_col1, info_col2 = st.columns(2)
with info_col1:
    st.write("**Department:**",            student["department"])
    st.write("**Year:**",                  student["year_label"])
with info_col2:
    st.write("**Recommended Category:**", student["recommended_intervention"])

st.divider()

# ── Risk factor chart ─────────────────────────────────────────────────────────
st.subheader("Risk Factor Analysis")

factors = pd.DataFrame({
    "Factor": ["Attendance", "Backlogs", "Fee Delay", "CGPA"],
    "Value": [
        student["attendance_percentage"],
        student["backlog_count"] * 10,
        student["fee_delay_days"],
        student["cgpa"] * 10
    ],
    "Color": ["blue", "red", "orange", "green"]
})

fig = px.bar(
    factors,
    x="Factor",
    y="Value",
    color="Color",
    color_discrete_map={
        "blue":   "#4C9BE8",
        "red":    "#E85C5C",
        "orange": "#E8A24C",
        "green":  "#4CE87A"
    },
    title=f"Risk factors for {selected_id}"
)
fig.update_layout(showlegend=False)
st.plotly_chart(fig, use_container_width=True)

st.divider()

# ── Intervention Plan (Person B's Mentor Agent API) ───────────────────────────
st.subheader("📋 Intervention Plan")
st.caption("Generated by the Mentor Agent — click below to fetch a plan for this student")

MENTOR_AGENT_URL = "http://localhost:8001/generate-intervention"

if st.button("Get Intervention Plan", use_container_width=False, key="get_intervention"):
    with st.spinner("Contacting Mentor Agent..."):
        try:
            import requests
            response = requests.post(
                MENTOR_AGENT_URL,
                json={"student_id": selected_id},
                timeout=15
            )
            response.raise_for_status()
            plan = response.json()

            # ── Summary card ──────────────────────────────────────────────────
            st.markdown("**Student Summary**")
            st.info(plan.get("student_summary", "—"))

            # ── Risk + priority badges ────────────────────────────────────────
            b1, b2, b3 = st.columns(3)
            b1.metric("Risk Band",     plan.get("risk_band", "—"))
            b2.metric("Risk Score",    plan.get("risk_score", "—"))
            b3.metric("Priority Level", plan.get("priority_level", "—"))

            st.divider()

            # ── Recommended actions ───────────────────────────────────────────
            st.markdown("**Recommended Actions**")
            actions = plan.get("recommended_actions", [])
            if actions:
                for i, action in enumerate(actions, 1):
                    st.markdown(f"{i}. {action}")
            else:
                st.write("No actions returned.")

            st.divider()

            # ── Follow-up plan ────────────────────────────────────────────────
            st.markdown("**Follow-up Plan**")
            st.warning(plan.get("follow_up_plan", "—"))

            # ── Approval status ───────────────────────────────────────────────
            status = plan.get("status", "—")
            if status == "pending_approval":
                st.markdown("**Approval Status:** 🟡 Pending Approval")
            elif status == "approved":
                st.markdown("**Approval Status:** 🟢 Approved")
            else:
                st.markdown(f"**Approval Status:** {status}")

        except requests.exceptions.ConnectionError:
            st.error("Could not reach the Mentor Agent. Make sure Person B's server is running on port 8001.")
        except requests.exceptions.Timeout:
            st.error("Request timed out. The Mentor Agent took too long to respond.")
        except requests.exceptions.HTTPError as e:
            st.error(f"API returned an error: {e}")
        except Exception as e:
            st.error(f"Unexpected error: {e}")